---
margin: 20
fullscreen_button:
  color: blue
  width: 100
  height: 40
  text: Fullscreen
  text_opts: &text_opts
    font:
      name: arial
      size: 16
      bold: true
      italic: false
    antialias: true
    color: white
    # left=0, centre=1, right=2
    align: 1
    # top=0, centre=1, bottom=2
    v_align: 1
close_button:
  color: blue
  width: 100
  height: 40
  text: Close
  text_opts: *text_opts
